sonarqube-backend-sast:
  stage: test
  rules:
    - changes:
      - backend/**/*
  image: maven:3.8-openjdk-16 
  script:
    - cd backend
    - >
      mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
      -Dsonar.projectName="09_${GITLAB_USER_NAME}_BACKEND"
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACKEND}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_BACKEND}
spotbugs-sast:
  
  variables:
    SAST_JAVA_VERSION: 11
    COMPILE: "false"
    MAVEN_REPO_PATH: $CI_PROJECT_DIR/backend/target/
  rules:
    - changes:
      - backend/**/*
  
    
eslint-sast:
  rules:
    - when: never
nodejs-scan-sast:
  rules:
    - when: never
semgrep-sast:
  rules:
    - changes:
      - backend/**/* 

