build-backend-code-job:
  stage: build  
  rules:
    - changes:
      - backend/*
  script:
    - echo JOB_ID=$CI_JOB_ID >> backend.env
    - echo JOB_NAME=$CI_JOB_NAME >> backend.env
    - cd backend
    - mvn package -Dversion.application=${VERSION}
    - echo CI_COMMIT_BRANCH
    - echo $CI_COMMIT_BRANCH
    - echo "${CI_COMMIT_BRANCH}"
  artifacts:
    name: "${CI_JOB_NAME}_${CI_JOB_ID}"
    paths:
      - backend/target/sausage-store-${VERSION}.jar
    reports:
      dotenv: backend.env
    expire_in: 1 week
notification-backend:
  
  extends:
    - .notification
  variables:
    TEXT_NOTIF: "backend"
  needs:
    - build-backend-code-job   
  



 

