build-backend-code-job:
  stage: build  
  rules:
    - changes:
      - backend/*
  script:
    - echo JOB_ID=$CI_JOB_ID >> backend.env
    - echo JOB_NAME=$CI_JOB_NAME >> backend.env
    - cd backend
    - mvn package
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    reports:
      dotenv: backend.env
    expire_in: 1 week
slack-notification-backend:
  rules:
    #- if: $CI_COMMIT_MESSAGE =~ /send notification/
    - changes:
      - backend/*
  extends:
    - .notification
  variables:
    JOB_NAME: "$JOB_NAME"
    JOB_ID: "$JOB_ID"
  needs:
    - build-backend-code-job   
  



 

