build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/*
  script:
    - echo "building backend"
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    expire_in: 1 week
slack-notification-backend:
  stage: notify
  only:
    changes:
    - backend/*
  script:
    - >
      curl 
      --request POST 
      --header "Content-type: application/json" 
      --data '{"blocks": [{"type": "section","text": {"type": "mrkdwn","text": "Собрана новая версия backend"}}]}'
      --url "https://hooks.slack.com/services/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"
      
  needs:
    - build-backend-code-job   

