build-backend-code-job:
  stage: build  
  rules:
    - changes:
      - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    expire_in: 1 week
sonarqube-backend-sast:
  stage: test
  rules:
    - changes:
      - backend/*
  image: maven:3.8-openjdk-16 
  script:
    - cd backend
    - >
      mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
      -Dsonar.projectName="needs_to_be_deleted"
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACKEND}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_BACKEND} 
slack-notification-backend:
  stage: notify
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/
      changes:
        - backend/*
  script:
    - >
      curl 
      --request POST 
      --header "Content-type: application/json" 
      --data '
      {"blocks":
      [
      {"type": "section","text": {"type": "mrkdwn","text": "Собрана новая версия backend"}},
      {"type": "actions","elements": [{"type": "button","text": {"type":"plain_text","text":"Скачать"},"style":"danger",
      "url":"'${CI_PROJECT_URL}'/-/jobs/artifacts/'${CI_COMMIT_REF_NAME}'/download?job=build-backend-code-job"}]}]}'
      --url "https://ch.cargoonline.ru/hooks/628dfc6d6dc4f90009fb8654/diQuoKGKYkDPnuLm4EnWLBLxNBjdsbBvwoir8Yaoc4h2bNFE"
      
  needs:
    - build-backend-code-job   

