build-backend-code-job:
  stage: build  
  rules:
    - changes:
      - backend/*
  script:
    - cd backend
    - mvn package -Dversion.application=${VERSION}
  cache:
    paths:
      - backend/target/sausage-store-${VERSION}.jar
    

upload-backend-release:
  stage: release
  rules:
    - changes:
      - backend/*
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - mvn -s settings.xml -Dversion.application=${VERSION} -DskipTests deploy

notification-backend:
  
  extends:
    - .notification
  variables:
    COMPONENT_NAME: "backend"
    LINK: ${NEXUS_REPO_URL}/sausage-store-Valerie-Shelgunova-backend/com/yandex/practicum/devops/sausage-store/${VERSION}/sausage-store-${VERSION}.jar
  needs:
    - build-backend-code-job   
  



 

