build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    expire_in: 1 week
sonarqube-backend-sast:
  stage: test
  only:
    changes:
    - backend/*
  image: maven:3.8-openjdk-16 
  script:
    - cd backend
    - >
      mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${SONAR_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN} 
slack-notification-backend:
  stage: notify
  only:
    changes:
    - backend/*
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/  
  script:
    - >
      curl 
      --request POST 
      --header "Content-type: application/json" 
      --data '
      {"blocks":
      [
      {"type": "section","text": {"type": "mrkdwn","text": "Собрана новая версия backend"}},
      {"type": "actions","elements": [{"type": "button","text": {"type":"plain_text","text":"Скачать"},"style":"danger",
      "url":"'${CI_PROJECT_URL}'/-/jobs/artifacts/'${CI_COMMIT_REF_NAME}'/download?job=build-backend-code-job"}]}]}'
      --url "https://hooks.slack.com/services/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"
      
  needs:
    - build-backend-code-job   

