build-backend-code-job:
  stage: build  
  rules:
    - changes:
      - backend/*
  script:
    - echo JOB_ID=$CI_JOB_ID >> backend.env
    - echo JOB_NAME=$CI_JOB_NAME >> backend.env
    - cd backend
    - mvn package -Dversion.application=${VERSION}
    
  artifacts:
    name: "${CI_JOB_NAME}_${CI_JOB_ID}"
    paths:
      - backend/target/sausage-store-${VERSION}.jar
    reports:
      dotenv: backend.env
    expire_in: 1 week

stages:
  - release

upload-backend-release:
  stage: release
  only:
    changes:
      - backend/*
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - mvn -s settings.xml -Dversion.application=${VERSION} -DskipTests deploy

notification-backend:
  
  extends:
    - .notification
  variables:
    TEXT_NOTIF: "backend"
  needs:
    - build-backend-code-job   
  



 

