build-frontend-code-job:
  stage: build  
  rules:
    - changes:
      - frontend/*
  script:
    - cd frontend
    - ls
    - npm install
    - npm run build
    - ls
    - cd dist
    - ls
  cache:
    paths:
      - frontend/dist/frontend

upload-frontend-release:
  stage: release
  rules:
    - changes:
      - frontend/*
  needs:
    - build-frontend-code-job
  script:
    - cd frontend
    - ls
    - tar czvf sausage-store-${VERSION}.tar.gz frontend
    - curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file sausage-store-${VERSION}.tar.gz ${NEXUS_REPO_URL}/sausage-store-Valerie-Shelgunova-frontend/sausage-store/${VERSION}/sausage-store-${VERSION}.tar.gz

notification-frontend:
  stage: notify
  rules:
    - changes:
      - frontend/*
  extends:
    - .notification
  variables:
    COMPONENT_NAME: "frontend"
    LINK: ${NEXUS_REPO_URL}/sausage-store-Valerie-Shelgunova-frontend/sausage-store/${VERSION}/sausage-store-${VERSION}.tar.gz"
  needs:
    - build-frontend-code-job   

