build-frontend-code-job:
  stage: build  
  only:
    changes:
    - frontend/*
  script:
    - echo JOB_ID=$CI_JOB_ID >> frontend.env
    - echo JOB_NAME=$CI_JOB_NAME >> frontend.env
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    name: "$CI_JOB_NAME"
    reports:
      dotenv: frontend.env
    paths:
      - frontend/dist/frontend
    expire_in: 1 week
slack-notification-frontend:
  stage: notify
  rules:
    - changes:
      - frontend/*
  extends:
    - .notification
  variables:
    TEXT_NOTIF: "frontend"
  needs:
    - build-frontend-code-job   

