sonarqube-frontend-sast:
  stage: test
  rules:
    - changes:
      - frontend/**/*
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner -Dsonar.qualitygate.wait=true
      -Dsonar.projectName="09_${GITLAB_USER_NAME}_FRONTEND"
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_FRONTEND}
      -Dsonar.sources=.
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_FRONTEND} 

spotbugs-sast:
  rules:
    - when: never
  
eslint-sast:
  rules:
    - changes:
      - frontend/**/*
nodejs-scan-sast:
  rules:
    - changes:
      - frontend/**/*
semgrep-sast:
  rules:
    - changes:
      - frontend/**/* 
      
