build-frontend-code-job:
  stage: build  
  only:
    changes:
    - frontend/*
  script:        
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - frontend/dist/frontend
    expire_in: 1 week

sonarqube-frontend-sast:
  stage: test
  rules:
    - changes:
      - frontend/*
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - echo 'VARIABLES:'
    - echo $GITLAB_USER_NAME
    - echo $GITLAB_USER_LOGIN
    - echo 09_${GITLAB_USER_NAME}_FRONTEND
    - echo $CI_JOB_NAME

    - cd frontend
    - >
      sonar-scanner -Dsonar.qualitygate.wait=true
      -Dsonar.projectName="'09_${GITLAB_USER_NAME}_FRONTEND'"
      -Dsonar.projectKey=${SONAR_PROJECT_KEY}
      -Dsonar.sources=.
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN} 

slack-notification-frontend:
  stage: notify
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/
      changes:
        - frontend/*
  script:
    - >
      curl 
      --request POST 
      --header "Content-type: application/json" 
      --data '
      {"blocks":
      [
      {"type": "section","text": {"type": "mrkdwn","text": "Собрана новая версия frontend"}},
      {"type": "actions","elements": [{"type": "button","text": {"type":"plain_text","text":"Скачать"},"style":"danger",
      "url":"'${CI_PROJECT_URL}'/-/jobs/artifacts/'${CI_COMMIT_REF_NAME}'/download?job=build-frontend-code-job"}]}]}'
      --url "https://hooks.slack.com/services/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"

  needs:
    - build-frontend-code-job   

