include:
  - template: Security/SAST.gitlab-ci.yml
build-frontend-code-job:
  stage: build  
  only:
    changes:
    - frontend/*
  script:        
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - frontend/dist/frontend
    expire_in: 1 week
sast:
  dependencies:
    - build-frontend-code-job
  stage: test
  rules:
    - when: never
  variables:
    SAST_EXCLUDED_ANALYZERS: "spotbugs"

slack-notification-frontend:
  stage: notify
  only:
    changes:
    - frontend/*
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/ 

  script:
    - >
      curl 
      --request POST 
      --header "Content-type: application/json" 
      --data '
      {"blocks":
      [
      {"type": "section","text": {"type": "mrkdwn","text": "Собрана новая версия frontend"}},
      {"type": "actions","elements": [{"type": "button","text": {"type":"plain_text","text":"Скачать"},"style":"danger",
      "url":"'${CI_PROJECT_URL}'/-/jobs/artifacts/'${CI_COMMIT_REF_NAME}'/download?job=build-frontend-code-job"}]}]}'
      --url "https://hooks.slack.com/services/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"

  needs:
    - build-frontend-code-job   

