.notification:
  stage: notify
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/
    - changes:
      - $TEXT_NOTIF/*

 
  script:
    - >
        DATA='{"blocks":
        [
        {"type": "section","text": {"type": "mrkdwn","text": "Собрана новая версия '${TEXT_NOTIF}'"}},
        {"type": "actions","elements": [{"type": "button","text": {"type":"plain_text","text":"Скачать"},"style":"danger",
        "url":"'${CI_PROJECT_URL}'/-/jobs/'${JOB_ID}'/artifacts/download"}]}]}'
        
    - echo "$DATA"
    - echo "$JOB_ID"
    - echo "$JOB_NAME"
    - echo $CI_PROJECT_DIR
    - echo "$CI_PROJECT_DIR"
    - echo "${CI_PROJECT_DIR}"
    - echo  ${CI_PROJECT_DIR}
    - >
      curl
      --request POST 
      --header "Content-type: application/json" 
      --data "$DATA"
      --url "$NOTIFICATION_URL"
 



   

