notification:
  stage: notify
  rules:
    #- if: $CI_COMMIT_MESSAGE =~ /send notification/
    #changes:
      #- backend/*

  variables:
    JOB_NAME: "undefined"
    JOB_ID: "undefined"
  script:
    - >
        DATA='{"blocks":
        [
        {"type": "section","text": {"type": "mrkdwn","text": "Собрана новая версия backend"}},
        {"type": "actions","elements": [{"type": "button","text": {"type":"plain_text","text":"Скачать"},"style":"danger",
        "url":"'${CI_PROJECT_URL}'/-/jobs/artifacts/'${CI_COMMIT_REF_NAME}'/download?job='${JOB_NAME}'"}]}]}'
        
    - echo "$DATA"
    - echo "$JOB_ID"
    - echo "$JOB_NAME"
    - >
      curl
      --request POST 
      --header "Content-type: application/json" 
      --data "$DATA"
      --url "$NOTIFICATION_URL"
 



   

