.notification:
  stage: notify
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/
      changes:
        - $TEXT_NOTIF/*

 
  script:
    - TEXT="Вышла новая версия '${TEXT_NOTIF}' сосисочной — '${VERSION}'. Скачать '${TEXT_NOTIF}' можно по ссылке — '${NEXUS_REPO_URL}com/yandex/practicum/devops/sausage-store/${VERSION}/sausage-store-${VERSION}.jar'"

    - echo $TEXT
    
    - >
        DATA='{"blocks":
        [
        {"type": "section","text": {"type": "mrkdwn","text": '${TEXT}'}},
        {"type": "actions","elements": [{"type": "button","text": {"type":"plain_text","text":"Скачать"},"style":"danger",
        "url":"'${CI_PROJECT_URL}'/-/jobs/'${JOB_ID}'/artifacts/download"}]}]}'

    - DATA='hop'

    - echo $DATA
    
    - >
      curl
      --request POST 
      --header "Content-type: application/json" 
      --data "$DATA"
      --url "$NOTIFICATION_URL"

    

 



   

