spotbugs-sast:
  
  variables:
    SAST_JAVA_VERSION: 11
    COMPILE: "false"
    MAVEN_REPO_PATH: $CI_PROJECT_DIR
  rules:
    - changes:
      - backend/*
  cache:
    key: backend
    paths:
      - backend/target/sausage-store-${VERSION}.jar
  artifacts:
    reports:
      sast: gl-sast-report.json

    
    
eslint-sast:
  rules:
    - changes:
      - frontend/*
nodejs-scan-sast:
  rules:
    - changes:
      - frontend/*
semgrep-sast:
  rules:
    - changes:
      - frontend/* 
      - backend/* 
