spotbugs-sast:
  dependencies:
    - build-backend-code-job
  variables:
    SAST_JAVA_VERSION: 11
    COMPILE: "false"
    MAVEN_REPO_PATH: $CI_PROJECT_DIR
  rules:
    - changes:
      - backend/*
  cache:
    
eslint-sast:
  rules:
    - changes:
      - frontend/*
nodejs-scan-sast:
  rules:
    - changes:
      - frontend/*
semgrep-sast:
  rules:
    - changes:
      - frontend/* 
      - backend/* 
